ImagePinned.Web/Controllers/ImageController.cs
using AutoMapper;
using ImagePinned.BLL.Interface;
using ImagePinned.BLL.EntitesDTO;
using ImagePinned.Web.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ListShop.Web.Validation;

namespace ImagePinned.Web.Controllers
{
    [ServerException]
    public class ImageController : Controller
    {

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private IService service
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IService>();
            }
        }
        // GET: Image
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Taped()
        {
            List<ImageDTOView> list = new List<ImageDTOView>(service.ImageGetAll());
            Mapper.Initialize(cfg => cfg.CreateMap<ImageDTOView, ImageModel>());
            var images =
               Mapper.Map<IEnumerable<ImageDTOView>, List<ImageModel>>(list);
            images.Reverse();
            return View(images);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase uploadImage, ImageView imageModel)
        {

            if (ModelState.IsValid && uploadImage != null)
            {
                byte[] imageData = null;

                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }
                imageModel.Resurse = imageData;
                try
                {
                    System.Drawing.Image x = (System.Drawing.Bitmap)((new System.Drawing.ImageConverter()).ConvertFrom(imageData));
                }
                catch (ArgumentException ex)
                {
                    return View();
                }
                Mapper.Initialize(cfg => cfg.CreateMap<ImageView, ImageDTO>().ForMember("Id_pin", opt => opt.MapFrom(c => 1)).ForMember("Id_Ownd", opt => opt.MapFrom(c => 1)));
                var imageDTO =
                   Mapper.Map<ImageView, ImageDTO>(imageModel);
                service.CreateImage(imageDTO, imageModel.Pin, AuthenticationManager.User.Identity.Name);
            }
            else
            {
                return View();
            }

            List<ImageDTOView> list = new List<ImageDTOView>(service.ImageGetAll());
            Mapper.Initialize(cfg => cfg.CreateMap<ImageDTOView, ImageModel>());
            var images =
               Mapper.Map<IEnumerable<ImageDTOView>, List<ImageModel>>(list);
            images.Reverse();
            return View("Taped", images);

        }

        [Authorize]

        public PartialViewResult Like(int Id)
        {

            ImageDTOView imageDTOView = service.GetImage(Id);
            Mapper.Initialize(cfg => cfg.CreateMap<ImageDTOView, ImageModel>());
            var images =
              Mapper.Map<ImageDTOView, ImageModel>(imageDTOView);

            if (service.isLike(AuthenticationManager.User.Identity.Name, images.Id))
            {
                images.Pin = "true";
            }
            else
            {
                images.Pin = "false";
            }

            return PartialView("Likes", images);
        }

        [HttpGet]
        public PartialViewResult Likes(int Id)
        {
            service.Like(AuthenticationManager.User.Identity.Name, Id);

            ImageDTOView imageDTOView = service.GetImage(Id);
            Mapper.Initialize(cfg => cfg.CreateMap<ImageDTOView, ImageModel>());
            var images =
              Mapper.Map<ImageDTOView, ImageModel>(imageDTOView);
            if (service.isLike(AuthenticationManager.User.Identity.Name, images.Id))
            {
                images.Pin = "true";
            }
            else
            {
                images.Pin = "false";
            }

            return PartialView(images);
        }

        [Authorize]
        public ActionResult Liked()
        {


            List<ImageDTOView> list = new List<ImageDTOView>(service.ImageGetLike(AuthenticationManager.User.Identity.Name));
            Mapper.Initialize(cfg => cfg.CreateMap<ImageDTOView, ImageModel>());
            var images =
               Mapper.Map<IEnumerable<ImageDTOView>, List<ImageModel>>(list);

            return View(images);

        }

        public PartialViewResult Category(string Pin, string Own)
        {
            if (Pin == null)
            {
                List<ImageDTOView> list = new List<ImageDTOView>(service.GetImage(Own));
                Mapper.Initialize(cfg => cfg.CreateMap<ImageDTOView, ImageModel>());
                var images =
                   Mapper.Map<IEnumerable<ImageDTOView>, List<ImageModel>>(list);
                images.Reverse();

                return PartialView(images);
            }
            else
            {
                List<ImageDTOView> list = new List<ImageDTOView>(service.ImageGetAll(Pin));
                Mapper.Initialize(cfg => cfg.CreateMap<ImageDTOView, ImageModel>());
                var images =
                   Mapper.Map<IEnumerable<ImageDTOView>, List<ImageModel>>(list);
                images.Reverse();

                return PartialView(images);
            }

        }

        [Authorize]
        public PartialViewResult ShowPrefer()
        {
            List<ImageDTOView> list = new List<ImageDTOView>(service.ImageGetPrefer(AuthenticationManager.User.Identity.Name));
            Mapper.Initialize(cfg => cfg.CreateMap<ImageDTOView, ImageModel>());
            var images =
               Mapper.Map<IEnumerable<ImageDTOView>, List<ImageModel>>(list);
            images.Reverse();

            return PartialView("Category", images);
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreatePin(string Pin)
        {
            service.CreatePin(Pin);
            List<ImageDTOView> list = new List<ImageDTOView>(service.ImageGetAll());
            Mapper.Initialize(cfg => cfg.CreateMap<ImageDTOView, ImageModel>());
            var images =
               Mapper.Map<IEnumerable<ImageDTOView>, List<ImageModel>>(list);
            images.Reverse();
            return View("Taped", images);
        }

    }
}

ImagePinned.Web/Views/Shared/UserLogin.cshtml
@model ImagePinned.Web.Models.UserViews
@if (Model.Email != null)
{
    if (Model.Role)
    {
        <li>@Html.ActionLink("AdminPanel", "AdminPanel", "Home")</li>
    }
    <li>@Html.ActionLink(@Model.Email,"Profiles","Home")</li>
    <li>@Html.ActionLink("Выход", "Logout", "Account")</li>

}
else
{
    <li>@Html.ActionLink("Вход", "Login", "Account")</li>
    <li>@Html.ActionLink("Регистрация", "Register", "Account")</li>
}

ImagePinned.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PinImage</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    
     <div class="container body-content">
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <nav class="navbar navbar-light bg-faded">
                            <a href="#" class="navbar-brand">
                                <img src="~/Resurce/icon.jpg"  width="30" height="30" alt=""/>
                            </a>
                            @Html.ActionLink("PinImage", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Рейтинг", "Rating", "Home", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Понравившиеся", "Liked", "Image", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Лента", "Taped", "Image", new { area = "" }, new { @class = "navbar-brand" })
                            <ul class="nav nav-pills pull-right">
                                @Html.Action("UserLogin", "Home")
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            @RenderBody()
            <hr />
            
        </div>

        <script src="~/Scripts/jquery-3.2.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>